steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPOSITORY_NAME:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPOSITORY_NAME:$COMMIT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nfl-games-app'         # Replace with your Cloud Run service name
      - '--image'
      - 'gcr.io/$PROJECT_ID/$REPOSITORY_NAME:$COMMIT_SHA'
      - '--region'
      - 'us-central1'               # Replace with your region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      

timeout: '600s'  # Increase the timeout as needed

# Define custom substitutions
substitutions:
  _REPOSITORY_NAME: 'meow' 

# Service account to use for this build
serviceAccount: projects/$PROJECT_ID/serviceAccounts/362530996210-compute@developer.gserviceaccount.com

# Add logging option
options:
  logging: NONE  # You can use NONE if you don't need logs