steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/meow-dev/dev:${COMMIT_SHA}', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/meow-dev/dev:${COMMIT_SHA}']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nfl-games-app-dev'         
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/meow-dev/dev:${COMMIT_SHA}'
      - '--region'
      - 'us-central1'               
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  

timeout: '600s'  

substitutions:
  _PROJECT_ID: '$PROJECT_ID'
  _COMMIT_SHA: '$COMMIT_SHA'

# Service account to use for this build
serviceAccount: projects/$PROJECT_ID/serviceAccounts/362530996210-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
